### ISSUE TITLE
sessions filter page

### ISSUE THREAD

**Issue by GaryRidgway** [ITS-UofIowa/iowasummerwritingfestival.org#4]
client wants some way to filter by specific session date ranges. they want to be able to:

- [x] enter specific date ranges (inclusive) for each session

- [x] tag individual events with session dates so that they can be grouped

- [x] have pages with the events from that session

- [x] add some way for users to easily access the festival page that contains the sessions and style that page to match the rest of the site

**Comment by GaryRidgway** [comment]
I would like to create a sidebar with the sessions and then also have a page with them just by themselves

**Comment by GaryRidgway** [comment]
After consideration of how this will function, I think the sidebar is no longer necessary, and we took a different approach to creating the solution including contextual filters through the view. In the long run this should create a more user friendly experience.

The last thing to do is to add some way for users to easily access the festival page that contains the sessions and style that page to match the rest of the site.

**Comment by genjohnson** [comment]
Regarding the fourth task, it looks like we can leverage the current Festival node that is being displayed on the homepage.
- [ ] Remove custom date/location configuration page & corresponding content on the front page.
- [ ] In display of Festival node on the front page, add a link to the full Festival node page.
- [ ] Style the Festival node on the front page
